### ISSUE TITLE
docs: Contributing pages for launch

### ISSUE THREAD

**Issue by Firgrep** [systemphil/sphil#7]
## Todo

**Contributions index page** 
- [ ] edit page/add Tutorial video for how to use gh from scratch following our contributions index page
- [x] ~~edit page/add a "basic github workflow" to our contributions index page~~ (redundant since we have a page for this)

**Github pages group**
- [x] add page/elaboration on github workflow

**Formatting pages group**
- [x] add page/markdown formatting
- [x] add page/advanced markdown formatting
- [x] add page/website(nextra) specific JSX component/formatting

**Local development**
- [x] add page/how to setup local development

**Comment by Firgrep** [comment]
Docs are mostly up. Now the video remains.
